<a href="https://colab.research.google.com/github/akshay-mohan-k/DeepLearning/blob/master/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import torch
print(torch.__version__)

2.9.0+cpu


In [31]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available")

GPU not available


Creating a Tensor


In [33]:
#using empty
torch.empty(2,3)

tensor([[1.4153e-43, 1.6255e-43, 1.3312e-43],
        [1.4013e-43, 1.4153e-43, 1.6535e-43]])

In [34]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [35]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])